// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

function run(comparatorOpt, message, left, right) {
  var comparator = comparatorOpt !== undefined ? comparatorOpt : Caml_obj.equal;
  if (Curry._2(comparator, left, right)) {
    console.log("🍀: " + message + "");
  } else {
    console.log("💥: " + message + "");
    console.log(left, "!=", right);
  }
}

exports.run = run;
/* No side effect */
